# Generated by Django 3.0.5 on 2021-02-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210213_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblcommonmasters',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='tblcontentmaster',
            name='image_url',
            field=models.ImageField(upload_to='', verbose_name='Thumbnails'),
        ),
        migrations.AlterField(
            model_name='tblcontentmaster',
            name='video',
            field=models.FileField(upload_to='', verbose_name='Audio/Video'),
        ),
    ]
